export interface IEditorData {
  [viewId: string | number]: {
    background: string;
    objects: any;
  };
}

export interface ITextWidget {
  type: string;
  originX: string;
  originY: string;
  left: number;
  top: number;
  width: number;
  height: number;
  fill: string;
  stroke: string;
  strokeWidth: 1;
  strokeDashArray: string;
  strokeLineCap: string;
  strokeLineJoin: string;
  strokeMiterLimit: number;
  scaleX: number;
  scaleY: number;
  angle: number;
  flipX: false;
  flipY: false;
  opacity: number;
  shadow: string;
  visible: boolean;
  clipTo: string;
  backgroundColor: string;
  fillRule: string;
  globalCompositeOperation: string;
  widgetType: string;
  widgetSubType: string;
  id: string;
  viewId: number;
  originalWidth: number;
  originalHeight: number;
  scaleFactor: number;
  customFilters: any;
  currentWidgetWidth: number;
  currentWidgetHeight: number;
  libProp: any;
  WidgetBorder: boolean;
  Rotate180Degree: boolean;
  caption: string;
  widget_key: string;
  group_key: string;
  price_key: string;
  shopbylogo_key: string;
  IsVisibleOnOutput: boolean;
  textSrc: string;
  textSrcLeft: number;
  textSrcTop: number;
  text: string;
  fontSize: number;
  fontWeight: string;
  fontFamily: string;
  fontStyle: string;
  lineHeight: string | number;
  textDecoration: string;
  textAlign: string;
  path: string;
  textBackgroundColor: string;
  vAlign: string;
  originalFontSize: number;
}

export interface IImageWidget {
  type: string;
  originX: string;
  originY: string;
  left: number;
  top: number;
  width: number;
  height: number;

  scaleX: number;
  scaleY: number;
  angle: number;
  flipX: boolean;
  flipY: boolean;
  opacity: number;
  shadow: string;
  visible: boolean;
  clipTo: string;
  backgroundColor: string;
  widgetType: string;
  widgetSubType: string;
  id: string;
  originalWidth: number;
  originalHeight: number;
  imageUniqueName: string;
  originalUrl: string;
  viewId: number;
  scaleFactor: number;
  cropArea: any;
  customFilters: any;
  currentWidgetWidth: number;
  currentWidgetHeight: number;
  ImageUniqueNameOnUGC: string;
  decalId: string;
  libProp: any;
  printImage: string;
  printImageMimeType: string;
  caption: string;
  widget_key: string;
  group_key: string;
  price_key: string;
  shopbylogo_key: string;
  WidgetBorder: boolean;
  Rotate180Degree: boolean;
  src: string;
  filters: any;
  crossOrigin: string;
  PreserveWidgetAspectRatio: boolean;
  PreserveImageAspectRatio: boolean;
  IsVisibleOnOutput: boolean;
}
